apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-snau17
  namespace: beta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-snau17
  template:
    metadata:
      labels:
        app: web-snau17
    spec:
      containers:
        - name: web-snau17
          image: dockeritc65/snau17-fe:v1.0.8
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: configinfo
              mountPath: /app/configs
      volumes:
        - name: configinfo
          configMap:
            name: cm-snau17-web-prod
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: web-snau17
  namespace: beta
spec:
  type: ClusterIP
  selector:
    app: web-snau17
  ports:
    - port: 3000
      targetPort: 3000
---

